name: uts
description: "Flutter Game Catalog with REST API FreeToGame"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.0
  url_launcher: ^6.3.0
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Jika kamu masih memakai gambar dari folder assets/images/
  # silakan aktifkan 2 baris di bawah
  #
  # assets:
  #   - assets/images/
